---
title: "Quantitative Methods for Urban Planners"
subtitle: "GSD SES 5215, Fall 2022"
output: tint::tintHtml
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Course textbook

[Regression and Other Stories](https://users.aalto.fi/~ave/ROS.pdf){target="_blank"}, but Gelman, Hill, and Vehtari

## Course topics

* Unit 1: Answering questions with quantitative methods
    * [Lecture 1](https://c-voulgaris.github.io/SES-5215-F22/unit-1/lecture-1.html){target="_blank"}
    * [Lecture 2](https://c-voulgaris.github.io/SES-5215-F22/unit-1/lecture-2.html){target="_blank"}
    * [Assignment 1: Select a dataset](https://c-voulgaris.github.io/SES-5215-F22/unit-1/assignment-1.html){target="_blank"}
    * [Lecture 3](https://c-voulgaris.github.io/SES-5215-F22/unit-1/lecture-3.html){target="_blank"}
* Unit 2: Visualizing data
    * [Lecture 4](https://c-voulgaris.github.io/SES-5215-F22/unit-2/lecture-4.html){target="_blank"}
    * [Assignment 2: Visualize data](https://c-voulgaris.github.io/SES-5215-F22/unit-2/assignment-2.html){target="_blank"}
    * [Lecture 5](https://c-voulgaris.github.io/SES-5215-F22/unit-2/lecture-5.html){target="_blank"}
* Unit 3: Hypothesis testing
    * [Lecture 6](https://c-voulgaris.github.io/SES-5215-F22/unit-3/lecture-6-R.html){target="_blank"}
    * [Assignment 3: Test for relationships](https://c-voulgaris.github.io/SES-5215-F22/unit-3/assignment-3.html){target="_blank"}
    * [Lecture 7](https://c-voulgaris.github.io/SES-5215-F22/unit-3/lecture-7.html){target="_blank"}
* Unit 4: Regression models
    * [Lecture 8](https://c-voulgaris.github.io/SES-5215-F22/unit-4/lecture-8.html){target="_blank"}
    * [Assignment 4: Duplicate hypothesis tests with regression](https://c-voulgaris.github.io/SES-5215-F22/unit-3/assignment-4.html){target="_blank"}
    * [Lecture 9](https://c-voulgaris.github.io/SES-5215-F22/unit-4/lecture-9.html){target="_blank"}
* Unit 5: Multiple regression
    * [Lecture 8](https://c-voulgaris.github.io/SES-5215-F22/unit-5/lecture-10.html){target="_blank"}
    * [Assignment 5: Estimate a multiple regression model](https://c-voulgaris.github.io/SES-5215-F22/unit-5/assignment-5.html){target="_blank"}

## Final project

For your final project, you will prepare a report with the 
following sections:

* Introduction: Present your research question, why it matters, and summarize
the answer.
* Data: Describe your data set.
* Methods: Explain the methods you use to analyze your data.
* Results: Present your results.
* Discussion: Explain what your results mean (and what they cannot
be interpretted to mean).
* Conclusion: Summarize your research question and its answer, and discuss
potential next steps.